/* Shared interface messages; game data and source labels remain unchanged. */
(()=>{
const messages={
"살포 영역 · 중앙 구는 디코이 1개 폭발 예시":{"ko": "살포 영역 · 중앙 구는 디코이 1개 폭발 예시", "en": "Deployment area · center sphere shows one decoy blast", "ja": "散布範囲・中央の球はデコイ1個の爆風例", "de": "Verteilungsfläche · mittlere Kugel: eine Köderexplosion", "es": "Zona de despliegue · esfera central: explosión de un señuelo", "fr": "Zone de déploiement · sphère centrale : explosion d’un leurre", "it": "Area di lancio · sfera centrale: esplosione di un diversivo", "nl": "Verspreidingsgebied · middelste bol: één explosie", "ru": "Зона разброса · в центре взрыв одной приманки", "zh-Hans": "投放区域 · 中央球体为单个诱饵爆炸示例", "zh-Hant": "投放區域 · 中央球體為單個誘餌爆炸示例"},
"본체·양쪽 주먹 배치 (평지 근사)":{"ko": "본체·양쪽 주먹 배치 (평지 근사)", "en": "Player and two fists (flat ground approximation)", "ja": "本体と左右の拳（平地での近似）", "de": "Spieler und zwei Fäuste (ebene Fläche, angenähert)", "es": "Jugador y dos puños (aproximación en llano)", "fr": "Joueur et deux poings (approximation sur sol plat)", "it": "Giocatore e due pugni (approssimazione su terreno piano)", "nl": "Speler en twee vuisten (benadering vlak terrein)", "ru": "Игрок и два кулака (приближение на ровной поверхности)", "zh-Hans": "本体及双拳位置（平地近似）", "zh-Hant": "本體及雙拳位置（平地近似）"},
"흡입 거리":{"ko": "흡입 거리", "en": "Suction reach", "ja": "吸引距離", "de": "Saugweite", "es": "Alcance de succión", "fr": "Portée d’aspiration", "it": "Portata di aspirazione", "nl": "Zuigbereik", "ru": "Дальность всасывания", "zh-Hans": "吸收距离", "zh-Hant": "吸收距離"},
"탄 도달 거리":{"ko": "탄 도달 거리", "en": "Projectile reach", "ja": "弾の到達距離", "de": "Geschossreichweite", "es": "Alcance del proyectil", "fr": "Portée du projectile", "it": "Gittata del proiettile", "nl": "Projectielbereik", "ru": "Дальность снаряда", "zh-Hans": "弹丸到达距离", "zh-Hant": "彈丸到達距離"},
"수평 최대 거리 착탄 예시":{"ko": "수평 최대 거리 착탄 예시", "en": "Impact at maximum horizontal range", "ja": "水平最大射程での着弾例", "de": "Einschlag bei maximaler horizontaler Reichweite", "es": "Impacto a máxima distancia horizontal", "fr": "Impact à portée horizontale maximale", "it": "Impatto alla massima gittata orizzontale", "nl": "Inslag op maximaal horizontaal bereik", "ru": "Попадание на максимальной горизонтальной дальности", "zh-Hans": "水平最大射程着弹示例", "zh-Hant": "水平最大射程著彈示例"},
"연사 사거리":{"ko": "연사 사거리", "en": "Rapid-fire range", "ja": "連射射程", "de": "Schnellfeuerreichweite", "es": "Alcance de disparo rápido", "fr": "Portée du tir rapide", "it": "Gittata del fuoco rapido", "nl": "Snelvuurbereik", "ru": "Дальность скорострельного огня", "zh-Hans": "连射射程", "zh-Hant": "連射射程"},
"차지 시간 ≈ {n}초 (평지 추정)":{"ko": "차지 시간 ≈ {n}초 (평지 추정)", "en": "Charge ≈ {n}s (flat ground estimate)", "ja": "チャージ約{n}秒（平地の目安）", "de": "Ladezeit ≈ {n}s (ebene Fläche, geschätzt)", "es": "Carga ≈ {n}s (estimación en llano)", "fr": "Charge ≈ {n}s (estimation sur sol plat)", "it": "Carica ≈ {n}s (stima su terreno piano)", "nl": "Opladen ≈ {n}s (schatting vlak terrein)", "ru": "Заряд ≈ {n}с (оценка для ровной поверхности)", "zh-Hans": "蓄力约 {n} 秒（平地估算）", "zh-Hant": "蓄力約 {n} 秒（平地估算）"},
"최대 차지 · 3연속 폭발":{"ko": "최대 차지 · 3연속 폭발", "en": "Full charge · 3 explosions", "ja": "最大チャージ・3連続爆発", "de": "Volle Ladung · 3 Explosionen", "es": "Carga máxima · 3 explosiones", "fr": "Charge maximale · 3 explosions", "it": "Carica massima · 3 esplosioni", "nl": "Volledig opgeladen · 3 explosies", "ru": "Полный заряд · 3 взрыва", "zh-Hans": "完全蓄力 · 连续3次爆炸", "zh-Hant": "完全蓄力 · 連續3次爆炸"},
"사거리 표시":{"ko": "사거리 표시", "en": "Range display", "ja": "射程表示", "de": "Reichweitenanzeige", "es": "Mostrar alcance", "fr": "Affichage de portée", "it": "Visualizzazione gittata", "nl": "Bereikweergave", "ru": "Отображение дальности", "zh-Hans": "射程显示", "zh-Hant": "射程顯示"},
"없음":{"ko": "없음", "en": "None", "ja": "なし", "de": "Keine", "es": "Ninguno", "fr": "Aucun", "it": "Nessuna", "nl": "Geen", "ru": "Нет", "zh-Hans": "无", "zh-Hant": "無"},
"기본":{"ko": "기본", "en": "Basic", "ja": "基本", "de": "Einfach", "es": "Básico", "fr": "Simple", "it": "Base", "nl": "Basis", "ru": "Базовый", "zh-Hans": "基本", "zh-Hant": "基本"},
"고급":{"ko": "고급", "en": "Advanced", "ja": "詳細", "de": "Erweitert", "es": "Avanzado", "fr": "Avancé", "it": "Avanzata", "nl": "Geavanceerd", "ru": "Расширенный", "zh-Hans": "高级", "zh-Hant": "進階"},

  "무기": {
    "ko": "무기",
    "en": "Weapons",
    "ja": "ブキ",
    "de": "Waffen",
    "es": "Armas",
    "fr": "Armes",
    "it": "Armi",
    "nl": "Wapens",
    "ru": "Оружие",
    "zh-Hans": "武器",
    "zh-Hant": "武器"
  },
  "스테이지": {
    "ko": "스테이지",
    "en": "Stages",
    "ja": "ステージ",
    "de": "Arenen",
    "es": "Escenarios",
    "fr": "Stages",
    "it": "Scenari",
    "nl": "Levels",
    "ru": "Арены",
    "zh-Hans": "场地",
    "zh-Hant": "場地"
  },
  "카탈로그": {
    "ko": "카탈로그",
    "en": "Catalogue",
    "ja": "カタログ",
    "de": "Katalog",
    "es": "Catálogo",
    "fr": "Catalogue",
    "it": "Catalogo",
    "nl": "Catalogus",
    "ru": "Каталог",
    "zh-Hans": "目录",
    "zh-Hant": "目錄"
  },
  "스플래툰 3 무기 데이터베이스": {
    "ko": "스플래툰 3 무기 데이터베이스",
    "en": "Splatoon 3 Weapon Database",
    "ja": "スプラトゥーン3 ブキデータベース",
    "de": "Splatoon 3 Waffendatenbank",
    "es": "Base de datos de armas de Splatoon 3",
    "fr": "Base de données des armes de Splatoon 3",
    "it": "Database delle armi di Splatoon 3",
    "nl": "Splatoon 3-wapendatabase",
    "ru": "База оружия Splatoon 3",
    "zh-Hans": "斯普拉遁3 武器数据库",
    "zh-Hant": "斯普拉遁3 武器資料庫"
  },
  "무기 목록": {
    "ko": "무기 목록",
    "en": "Weapon list",
    "ja": "ブキ一覧",
    "de": "Waffenliste",
    "es": "Lista de armas",
    "fr": "Liste des armes",
    "it": "Elenco armi",
    "nl": "Wapenlijst",
    "ru": "Список оружия",
    "zh-Hans": "武器列表",
    "zh-Hant": "武器清單"
  },
  "스테이지 검색": {
    "ko": "스테이지 검색",
    "en": "Find a stage",
    "ja": "ステージを探す",
    "de": "Arena suchen",
    "es": "Buscar escenario",
    "fr": "Chercher un stage",
    "it": "Cerca scenario",
    "nl": "Level zoeken",
    "ru": "Найти арену",
    "zh-Hans": "搜索场地",
    "zh-Hant": "搜尋場地"
  },
  "스테이지 이름": {
    "ko": "스테이지 이름",
    "en": "Stage name",
    "ja": "ステージ名",
    "de": "Arenaname",
    "es": "Nombre del escenario",
    "fr": "Nom du stage",
    "it": "Nome dello scenario",
    "nl": "Levelnaam",
    "ru": "Название арены",
    "zh-Hans": "场地名称",
    "zh-Hant": "場地名稱"
  },
  "종류": {
    "ko": "종류",
    "en": "Category",
    "ja": "種類",
    "de": "Kategorie",
    "es": "Categoría",
    "fr": "Catégorie",
    "it": "Categoria",
    "nl": "Categorie",
    "ru": "Категория",
    "zh-Hans": "类别",
    "zh-Hant": "類別"
  },
  "대전": {
    "ko": "대전",
    "en": "Battle",
    "ja": "バトル",
    "de": "Kampf",
    "es": "Combate",
    "fr": "Combat",
    "it": "Battaglia",
    "nl": "Gevecht",
    "ru": "Бой",
    "zh-Hans": "对战",
    "zh-Hant": "對戰"
  },
  "연어런": {
    "ko": "연어런",
    "en": "Salmon Run",
    "ja": "サーモンラン",
    "de": "Salmon Run",
    "es": "Salmon Run",
    "fr": "Salmon Run",
    "it": "Salmon Run",
    "nl": "Salmon Run",
    "ru": "Лососевый забег",
    "zh-Hans": "鲑鱼跑",
    "zh-Hant": "鮭魚跑"
  },
  "빅 런": {
    "ko": "빅 런",
    "en": "Big Run",
    "ja": "ビッグラン",
    "de": "Big Run",
    "es": "Big Run",
    "fr": "Big Run",
    "it": "Big Run",
    "nl": "Big Run",
    "ru": "Большой забег",
    "zh-Hans": "大型跑",
    "zh-Hant": "大型跑"
  },
  "스테이지를 불러오는 중…": {
    "ko": "스테이지를 불러오는 중…",
    "en": "Loading stages…",
    "ja": "ステージを読み込み中…",
    "de": "Arenen werden geladen…",
    "es": "Cargando escenarios…",
    "fr": "Chargement des stages…",
    "it": "Caricamento scenari…",
    "nl": "Levels laden…",
    "ru": "Загрузка арен…",
    "zh-Hans": "正在加载场地…",
    "zh-Hant": "正在載入場地…"
  },
  "스테이지 목록": {
    "ko": "스테이지 목록",
    "en": "Stage list",
    "ja": "ステージ一覧",
    "de": "Arenaliste",
    "es": "Lista de escenarios",
    "fr": "Liste des stages",
    "it": "Elenco scenari",
    "nl": "Levellijst",
    "ru": "Список арен",
    "zh-Hans": "场地列表",
    "zh-Hant": "場地清單"
  },
  "일치하는 스테이지가 없습니다.": {
    "ko": "일치하는 스테이지가 없습니다.",
    "en": "No matching stages.",
    "ja": "該当するステージがありません。",
    "de": "Keine passenden Arenen.",
    "es": "No hay escenarios coincidentes.",
    "fr": "Aucun stage correspondant.",
    "it": "Nessuno scenario corrispondente.",
    "nl": "Geen overeenkomende levels.",
    "ru": "Подходящих арен нет.",
    "zh-Hans": "没有匹配的场地。",
    "zh-Hant": "沒有符合的場地。"
  },
  "목록을 불러오지 못했습니다.": {
    "ko": "목록을 불러오지 못했습니다.",
    "en": "Could not load the list.",
    "ja": "一覧を読み込めませんでした。",
    "de": "Liste konnte nicht geladen werden.",
    "es": "No se pudo cargar la lista.",
    "fr": "Impossible de charger la liste.",
    "it": "Impossibile caricare l’elenco.",
    "nl": "De lijst kon niet worden geladen.",
    "ru": "Не удалось загрузить список.",
    "zh-Hans": "无法加载列表。",
    "zh-Hant": "無法載入清單。"
  },
  "← 목록으로": {
    "ko": "← 목록으로",
    "en": "← Back to list",
    "ja": "← 一覧へ",
    "de": "← Zur Liste",
    "es": "← Volver a la lista",
    "fr": "← Retour à la liste",
    "it": "← Torna all’elenco",
    "nl": "← Terug naar lijst",
    "ru": "← К списку",
    "zh-Hans": "← 返回列表",
    "zh-Hant": "← 返回清單"
  },
  "룰": {
    "ko": "룰",
    "en": "Mode",
    "ja": "ルール",
    "de": "Modus",
    "es": "Modo",
    "fr": "Mode",
    "it": "Modalità",
    "nl": "Speltype",
    "ru": "Режим",
    "zh-Hans": "规则",
    "zh-Hant": "規則"
  },
  "수위": {
    "ko": "수위",
    "en": "Tide",
    "ja": "潮位",
    "de": "Wasserstand",
    "es": "Marea",
    "fr": "Marée",
    "it": "Marea",
    "nl": "Getij",
    "ru": "Уровень воды",
    "zh-Hans": "潮位",
    "zh-Hant": "潮位"
  },
  "5개 룰": {
    "ko": "5개 룰",
    "en": "5 modes",
    "ja": "5ルール",
    "de": "5 Modi",
    "es": "5 modos",
    "fr": "5 modes",
    "it": "5 modalità",
    "nl": "5 speltypen",
    "ru": "5 режимов",
    "zh-Hans": "5种规则",
    "zh-Hant": "5種規則"
  },
  "3개 수위": {
    "ko": "3개 수위",
    "en": "3 tides",
    "ja": "3つの潮位",
    "de": "3 Wasserstände",
    "es": "3 mareas",
    "fr": "3 marées",
    "it": "3 maree",
    "nl": "3 getijden",
    "ru": "3 уровня воды",
    "zh-Hans": "3种潮位",
    "zh-Hant": "3種潮位"
  },
  "영역 배틀": {
    "ko": "영역 배틀",
    "en": "Turf War",
    "ja": "ナワバリバトル",
    "de": "Revierkampf",
    "es": "Combate territorial",
    "fr": "Guerre de territoire",
    "it": "Mischie mollusche",
    "nl": "Grondoorlog",
    "ru": "Бой салаг",
    "zh-Hans": "占地对战",
    "zh-Hant": "占地對戰"
  },
  "랭크 에어리어": {
    "ko": "랭크 에어리어",
    "en": "Splat Zones",
    "ja": "ガチエリア",
    "de": "Herrschaft",
    "es": "Pintazonas",
    "fr": "Défense de zone",
    "it": "Zona splat",
    "nl": "Spetterzone",
    "ru": "Бой за зоны",
    "zh-Hans": "真格区域",
    "zh-Hant": "真格區域"
  },
  "랭크 타워": {
    "ko": "랭크 타워",
    "en": "Tower Control",
    "ja": "ガチヤグラ",
    "de": "Turmkommando",
    "es": "Torre",
    "fr": "Expédition risquée",
    "it": "Torre mobile",
    "nl": "Torentwist",
    "ru": "Бой за башню",
    "zh-Hans": "真格塔楼",
    "zh-Hant": "真格塔樓"
  },
  "랭크 피시 배틀": {
    "ko": "랭크 피시 배틀",
    "en": "Rainmaker",
    "ja": "ガチホコバトル",
    "de": "Operation Goldfisch",
    "es": "Pez dorado",
    "fr": "Mission Bazookarpe",
    "it": "Bazookarp",
    "nl": "Bazookarper",
    "ru": "Мегакарп",
    "zh-Hans": "真格鱼虎对战",
    "zh-Hant": "真格魚虎對戰"
  },
  "랭크 바지락": {
    "ko": "랭크 바지락",
    "en": "Clam Blitz",
    "ja": "ガチアサリ",
    "de": "Muschelchaos",
    "es": "Asalto almeja",
    "fr": "Pluie de palourdes",
    "it": "Vongol gol",
    "nl": "Schelpenstrijd",
    "ru": "Устричный блиц",
    "zh-Hans": "真格蛤蜊",
    "zh-Hant": "真格蛤蜊"
  },
  "간조": {
    "ko": "간조",
    "en": "Low tide",
    "ja": "干潮",
    "de": "Ebbe",
    "es": "Marea baja",
    "fr": "Marée basse",
    "it": "Bassa marea",
    "nl": "Laagwater",
    "ru": "Отлив",
    "zh-Hans": "干潮",
    "zh-Hant": "乾潮"
  },
  "일반": {
    "ko": "일반",
    "en": "Normal tide",
    "ja": "通常潮",
    "de": "Normaler Wasserstand",
    "es": "Marea normal",
    "fr": "Marée normale",
    "it": "Marea normale",
    "nl": "Normaal water",
    "ru": "Обычный уровень",
    "zh-Hans": "普通潮",
    "zh-Hant": "普通潮"
  },
  "만조": {
    "ko": "만조",
    "en": "High tide",
    "ja": "満潮",
    "de": "Flut",
    "es": "Marea alta",
    "fr": "Marée haute",
    "it": "Alta marea",
    "nl": "Hoogwater",
    "ru": "Прилив",
    "zh-Hans": "满潮",
    "zh-Hant": "滿潮"
  },
  "무기 배치와 사거리": {
    "ko": "무기 배치와 사거리",
    "en": "Weapon placement and range",
    "ja": "ブキの配置と射程",
    "de": "Waffenplatzierung und Reichweite",
    "es": "Posición y alcance de armas",
    "fr": "Placement et portée des armes",
    "it": "Posizionamento e portata armi",
    "nl": "Wapenplaatsing en bereik",
    "ru": "Размещение и дальность оружия",
    "zh-Hans": "武器放置与射程",
    "zh-Hant": "武器放置與射程"
  },
  "마커를 지도로 드래그해서 배치할 수 있어요.": {
    "ko": "마커를 지도로 드래그해서 배치할 수 있어요.",
    "en": "Drag a marker onto the map to place it.",
    "ja": "マーカーをマップにドラッグして配置できます。",
    "de": "Ziehe einen Marker auf die Karte, um ihn zu platzieren.",
    "es": "Arrastra un marcador al mapa para colocarlo.",
    "fr": "Faites glisser un marqueur sur la carte pour le placer.",
    "it": "Trascina un indicatore sulla mappa per posizionarlo.",
    "nl": "Sleep een markering naar de kaart om deze te plaatsen.",
    "ru": "Перетащите маркер на карту, чтобы разместить его.",
    "zh-Hans": "将标记拖到地图上即可放置。",
    "zh-Hant": "將標記拖曳至地圖上即可放置。"
  },
  "무기 카테고리": {
    "ko": "무기 카테고리",
    "en": "Weapon categories",
    "ja": "ブキのカテゴリー",
    "de": "Waffenkategorien",
    "es": "Categorías de armas",
    "fr": "Catégories d’armes",
    "it": "Categorie di armi",
    "nl": "Wapencategorieën",
    "ru": "Категории оружия",
    "zh-Hans": "武器类别",
    "zh-Hant": "武器類別"
  },
  "무기 팔레트": {
    "ko": "무기 팔레트",
    "en": "Weapon palette",
    "ja": "ブキパレット",
    "de": "Waffenpalette",
    "es": "Paleta de armas",
    "fr": "Palette d’armes",
    "it": "Tavolozza armi",
    "nl": "Wapenpalet",
    "ru": "Палитра оружия",
    "zh-Hans": "武器面板",
    "zh-Hant": "武器面板"
  },
  "무기 다시 불러오기": {
    "ko": "무기 다시 불러오기",
    "en": "Reload weapons",
    "ja": "ブキを再読み込み",
    "de": "Waffen neu laden",
    "es": "Recargar armas",
    "fr": "Recharger les armes",
    "it": "Ricarica armi",
    "nl": "Wapens opnieuw laden",
    "ru": "Перезагрузить оружие",
    "zh-Hans": "重新加载武器",
    "zh-Hant": "重新載入武器"
  },
  "이동하고 회전할 수 있는 스테이지": {
    "ko": "이동하고 회전할 수 있는 스테이지",
    "en": "Pannable and rotatable stage",
    "ja": "移動・回転できるステージ",
    "de": "Verschiebbare und drehbare Arena",
    "es": "Escenario desplazable y giratorio",
    "fr": "Stage déplaçable et pivotant",
    "it": "Scenario spostabile e ruotabile",
    "nl": "Verschuifbaar en draaibaar level",
    "ru": "Арена с перемещением и вращением",
    "zh-Hans": "可移动和旋转的场地",
    "zh-Hant": "可移動和旋轉的場地"
  },
  "룰 목표 위치와 경로": {
    "ko": "룰 목표 위치와 경로",
    "en": "Mode objectives and routes",
    "ja": "ルールの目標位置とルート",
    "de": "Modusziele und Routen",
    "es": "Objetivos y rutas del modo",
    "fr": "Objectifs et parcours du mode",
    "it": "Obiettivi e percorsi della modalità",
    "nl": "Speldoelen en routes",
    "ru": "Цели режима и маршруты",
    "zh-Hans": "规则目标位置与路线",
    "zh-Hant": "規則目標位置與路線"
  },
  "배치한 무기": {
    "ko": "배치한 무기",
    "en": "Placed weapons",
    "ja": "配置したブキ",
    "de": "Platzierte Waffen",
    "es": "Armas colocadas",
    "fr": "Armes placées",
    "it": "Armi posizionate",
    "nl": "Geplaatste wapens",
    "ru": "Размещённое оружие",
    "zh-Hans": "已放置的武器",
    "zh-Hant": "已放置的武器"
  },
  "지형을 불러오는 중…": {
    "ko": "지형을 불러오는 중…",
    "en": "Loading terrain…",
    "ja": "地形を読み込み中…",
    "de": "Gelände wird geladen…",
    "es": "Cargando terreno…",
    "fr": "Chargement du terrain…",
    "it": "Caricamento terreno…",
    "nl": "Terrein laden…",
    "ru": "Загрузка рельефа…",
    "zh-Hans": "正在加载地形…",
    "zh-Hant": "正在載入地形…"
  },
  "드래그 조작": {
    "ko": "드래그 조작",
    "en": "Drag controls",
    "ja": "ドラッグ操作",
    "de": "Ziehsteuerung",
    "es": "Controles de arrastre",
    "fr": "Commandes de glissement",
    "it": "Comandi di trascinamento",
    "nl": "Sleepbediening",
    "ru": "Управление перетаскиванием",
    "zh-Hans": "拖动操作",
    "zh-Hant": "拖曳操作"
  },
  "이동": {
    "ko": "이동",
    "en": "Pan",
    "ja": "移動",
    "de": "Verschieben",
    "es": "Mover",
    "fr": "Déplacer",
    "it": "Sposta",
    "nl": "Verplaatsen",
    "ru": "Перемещение",
    "zh-Hans": "移动",
    "zh-Hant": "移動"
  },
  "회전": {
    "ko": "회전",
    "en": "Rotate",
    "ja": "回転",
    "de": "Drehen",
    "es": "Girar",
    "fr": "Pivoter",
    "it": "Ruota",
    "nl": "Draaien",
    "ru": "Вращение",
    "zh-Hans": "旋转",
    "zh-Hant": "旋轉"
  },
  "오른쪽 드래그로도 회전할 수 있어요": {
    "ko": "오른쪽 드래그로도 회전할 수 있어요",
    "en": "You can also right-drag to rotate",
    "ja": "右ドラッグでも回転できます",
    "de": "Auch mit der rechten Maustaste ziehen, um zu drehen",
    "es": "También puedes arrastrar con el botón derecho para girar",
    "fr": "Vous pouvez aussi faire glisser avec le bouton droit pour pivoter",
    "it": "Puoi anche trascinare con il tasto destro per ruotare",
    "nl": "Je kunt ook met de rechtermuisknop slepen om te draaien",
    "ru": "Также можно вращать правой кнопкой мыши",
    "zh-Hans": "也可以按住右键拖动来旋转",
    "zh-Hant": "也可以按住右鍵拖曳來旋轉"
  },
  "직교 투영 켜기/끄기": {
    "ko": "직교 투영 켜기/끄기",
    "en": "Toggle orthographic projection",
    "ja": "平行投影の切り替え",
    "de": "Orthografische Projektion umschalten",
    "es": "Alternar proyección ortográfica",
    "fr": "Activer/désactiver la projection orthographique",
    "it": "Attiva/disattiva proiezione ortografica",
    "nl": "Orthografische projectie omschakelen",
    "ru": "Переключить ортографическую проекцию",
    "zh-Hans": "切换正交投影",
    "zh-Hant": "切換正交投影"
  },
  "직교": {
    "ko": "직교",
    "en": "Orthographic",
    "ja": "平行投影",
    "de": "Orthografisch",
    "es": "Ortográfica",
    "fr": "Orthographique",
    "it": "Ortografica",
    "nl": "Orthografisch",
    "ru": "Ортографическая",
    "zh-Hans": "正交",
    "zh-Hant": "正交"
  },
  "원근": {
    "ko": "원근",
    "en": "Perspective",
    "ja": "透視投影",
    "de": "Perspektivisch",
    "es": "Perspectiva",
    "fr": "Perspective",
    "it": "Prospettica",
    "nl": "Perspectief",
    "ru": "Перспективная",
    "zh-Hans": "透视",
    "zh-Hant": "透視"
  },
  "카메라 리셋": {
    "ko": "카메라 리셋",
    "en": "Reset camera",
    "ja": "カメラをリセット",
    "de": "Kamera zurücksetzen",
    "es": "Restablecer cámara",
    "fr": "Réinitialiser la caméra",
    "it": "Ripristina fotocamera",
    "nl": "Camera herstellen",
    "ru": "Сбросить камеру",
    "zh-Hans": "重置相机",
    "zh-Hant": "重設攝影機"
  },
  "전체 보기": {
    "ko": "전체 보기",
    "en": "Fit map",
    "ja": "全体表示",
    "de": "Ganze Karte",
    "es": "Ver todo el mapa",
    "fr": "Voir toute la carte",
    "it": "Mostra tutta la mappa",
    "nl": "Hele kaart",
    "ru": "Показать всю карту",
    "zh-Hans": "查看全图",
    "zh-Hant": "檢視全圖"
  },
  "높은 지형 숨기기": {
    "ko": "높은 지형 숨기기",
    "en": "Hide high terrain",
    "ja": "高い地形を隠す",
    "de": "Hohes Gelände ausblenden",
    "es": "Ocultar terreno elevado",
    "fr": "Masquer les terrains élevés",
    "it": "Nascondi terreno elevato",
    "nl": "Hoog terrein verbergen",
    "ru": "Скрыть высокий рельеф",
    "zh-Hans": "隐藏高处地形",
    "zh-Hant": "隱藏高處地形"
  },
  "높은 지형 표시": {
    "ko": "높은 지형 표시",
    "en": "Show high terrain",
    "ja": "高い地形を表示",
    "de": "Hohes Gelände anzeigen",
    "es": "Mostrar terreno elevado",
    "fr": "Afficher les terrains élevés",
    "it": "Mostra terreno elevato",
    "nl": "Hoog terrein tonen",
    "ru": "Показать высокий рельеф",
    "zh-Hans": "显示高处地形",
    "zh-Hant": "顯示高處地形"
  },
  "모두 지우기": {
    "ko": "모두 지우기",
    "en": "Clear all",
    "ja": "すべて消去",
    "de": "Alle entfernen",
    "es": "Borrar todo",
    "fr": "Tout effacer",
    "it": "Cancella tutto",
    "nl": "Alles wissen",
    "ru": "Удалить всё",
    "zh-Hans": "全部清除",
    "zh-Hant": "全部清除"
  },
  "확대": {
    "ko": "확대",
    "en": "Zoom in",
    "ja": "拡大",
    "de": "Vergrößern",
    "es": "Acercar",
    "fr": "Agrandir",
    "it": "Ingrandisci",
    "nl": "Inzoomen",
    "ru": "Приблизить",
    "zh-Hans": "放大",
    "zh-Hant": "放大"
  },
  "축소": {
    "ko": "축소",
    "en": "Zoom out",
    "ja": "縮小",
    "de": "Verkleinern",
    "es": "Alejar",
    "fr": "Réduire",
    "it": "Riduci",
    "nl": "Uitzoomen",
    "ru": "Отдалить",
    "zh-Hans": "缩小",
    "zh-Hant": "縮小"
  },
  "드래그해서 이동 · 휠 / 두 손가락으로 확대": {
    "ko": "드래그해서 이동 · 휠 / 두 손가락으로 확대",
    "en": "Drag to pan · Wheel / pinch to zoom",
    "ja": "ドラッグで移動 · ホイール／ピンチで拡大縮小",
    "de": "Ziehen zum Verschieben · Mausrad / Pinch zum Zoomen",
    "es": "Arrastra para mover · Rueda / pellizca para ampliar",
    "fr": "Glisser pour déplacer · Molette / pincement pour zoomer",
    "it": "Trascina per spostare · Rotella / pizzica per zoomare",
    "nl": "Sleep om te verplaatsen · Wiel / knijp om te zoomen",
    "ru": "Перетаскивание — перемещение · Колесо / щипок — масштаб",
    "zh-Hans": "拖动以移动 · 滚轮／双指缩放",
    "zh-Hant": "拖曳以移動 · 滾輪／雙指縮放"
  },
  "드래그해서 회전 · 휠 / 두 손가락으로 확대": {
    "ko": "드래그해서 회전 · 휠 / 두 손가락으로 확대",
    "en": "Drag to rotate · Wheel / pinch to zoom",
    "ja": "ドラッグで回転 · ホイール／ピンチで拡大縮小",
    "de": "Ziehen zum Drehen · Mausrad / Pinch zum Zoomen",
    "es": "Arrastra para girar · Rueda / pellizca para ampliar",
    "fr": "Glisser pour pivoter · Molette / pincement pour zoomer",
    "it": "Trascina per ruotare · Rotella / pizzica per zoomare",
    "nl": "Sleep om te draaien · Wiel / knijp om te zoomen",
    "ru": "Перетаскивание — вращение · Колесо / щипок — масштаб",
    "zh-Hans": "拖动以旋转 · 滚轮／双指缩放",
    "zh-Hant": "拖曳以旋轉 · 滾輪／雙指縮放"
  },
  "사거리 출처": {
    "ko": "사거리 출처",
    "en": "Range source",
    "ja": "射程の出典",
    "de": "Reichweitenquelle",
    "es": "Fuente del alcance",
    "fr": "Source des portées",
    "it": "Fonte delle portate",
    "nl": "Bron van bereikgegevens",
    "ru": "Источник дальности",
    "zh-Hans": "射程来源",
    "zh-Hant": "射程來源"
  },
  "추출 데이터 v11.2.0 · 지형 미리보기": {
    "ko": "추출 데이터 v11.2.0 · 지형 미리보기",
    "en": "Extracted data v11.2.0 · Terrain preview",
    "ja": "抽出データ v11.2.0 · 地形プレビュー",
    "de": "Extrahierte Daten v11.2.0 · Geländevorschau",
    "es": "Datos extraídos v11.2.0 · Vista previa del terreno",
    "fr": "Données extraites v11.2.0 · Aperçu du terrain",
    "it": "Dati estratti v11.2.0 · Anteprima terreno",
    "nl": "Geëxtraheerde gegevens v11.2.0 · Terreinvoorbeeld",
    "ru": "Извлечённые данные v11.2.0 · Просмотр рельефа",
    "zh-Hans": "提取数据 v11.2.0 · 地形预览",
    "zh-Hant": "擷取資料 v11.2.0 · 地形預覽"
  },
  "지형을 불러오지 못했습니다. 다시 시도해 주세요.": {
    "ko": "지형을 불러오지 못했습니다. 다시 시도해 주세요.",
    "en": "Could not load terrain. Please retry.",
    "ja": "地形を読み込めませんでした。再試行してください。",
    "de": "Gelände konnte nicht geladen werden. Bitte erneut versuchen.",
    "es": "No se pudo cargar el terreno. Inténtalo de nuevo.",
    "fr": "Impossible de charger le terrain. Réessayez.",
    "it": "Impossibile caricare il terreno. Riprova.",
    "nl": "Terrein kon niet worden geladen. Probeer opnieuw.",
    "ru": "Не удалось загрузить рельеф. Повторите попытку.",
    "zh-Hans": "无法加载地形，请重试。",
    "zh-Hant": "無法載入地形，請重試。"
  },
  "압축 지형을 열 수 없습니다. 최신 브라우저로 열어 주세요.": {
    "ko": "압축 지형을 열 수 없습니다. 최신 브라우저로 열어 주세요.",
    "en": "Cannot decompress terrain. Use an up-to-date browser.",
    "ja": "地形を展開できません。最新のブラウザーを使用してください。",
    "de": "Gelände kann nicht entpackt werden. Bitte aktuellen Browser verwenden.",
    "es": "No se puede descomprimir el terreno. Usa un navegador actualizado.",
    "fr": "Impossible de décompresser le terrain. Utilisez un navigateur à jour.",
    "it": "Impossibile decomprimere il terreno. Usa un browser aggiornato.",
    "nl": "Kan terrein niet uitpakken. Gebruik een bijgewerkte browser.",
    "ru": "Не удалось распаковать рельеф. Обновите браузер.",
    "zh-Hans": "无法解压地形，请使用最新版浏览器。",
    "zh-Hant": "無法解壓縮地形，請使用最新版瀏覽器。"
  },
  "화면 연결이 끊겼습니다. 페이지를 새로고침해 주세요.": {
    "ko": "화면 연결이 끊겼습니다. 페이지를 새로고침해 주세요.",
    "en": "Graphics connection lost. Reload the page.",
    "ja": "描画接続が失われました。ページを再読み込みしてください。",
    "de": "Grafikverbindung verloren. Bitte Seite neu laden.",
    "es": "Se perdió la conexión gráfica. Recarga la página.",
    "fr": "Connexion graphique perdue. Rechargez la page.",
    "it": "Connessione grafica persa. Ricarica la pagina.",
    "nl": "Grafische verbinding verbroken. Herlaad de pagina.",
    "ru": "Графическое соединение потеряно. Обновите страницу.",
    "zh-Hans": "图形连接已断开，请刷新页面。",
    "zh-Hant": "圖形連線已中斷，請重新整理頁面。"
  },
  "이 브라우저에서는 3D 화면을 열 수 없습니다. 다른 브라우저로 열어주세요.": {
    "ko": "이 브라우저에서는 3D 화면을 열 수 없습니다. 다른 브라우저로 열어주세요.",
    "en": "3D view is unavailable. Try another browser.",
    "ja": "3D表示に対応していません。別のブラウザーを使用してください。",
    "de": "3D-Ansicht nicht verfügbar. Bitte anderen Browser verwenden.",
    "es": "Vista 3D no disponible. Prueba otro navegador.",
    "fr": "Vue 3D indisponible. Essayez un autre navigateur.",
    "it": "Vista 3D non disponibile. Prova un altro browser.",
    "nl": "3D-weergave niet beschikbaar. Probeer een andere browser.",
    "ru": "3D-просмотр недоступен. Попробуйте другой браузер.",
    "zh-Hans": "无法显示3D画面，请尝试其他浏览器。",
    "zh-Hant": "無法顯示3D畫面，請嘗試其他瀏覽器。"
  },
  "화면 준비에 실패했습니다.": {
    "ko": "화면 준비에 실패했습니다.",
    "en": "Could not prepare the view.",
    "ja": "画面を準備できませんでした。",
    "de": "Ansicht konnte nicht vorbereitet werden.",
    "es": "No se pudo preparar la vista.",
    "fr": "Impossible de préparer la vue.",
    "it": "Impossibile preparare la vista.",
    "nl": "Weergave kon niet worden voorbereid.",
    "ru": "Не удалось подготовить изображение.",
    "zh-Hans": "无法准备画面。",
    "zh-Hant": "無法準備畫面。"
  },
  "무기 목록을 불러오지 못했습니다.": {
    "ko": "무기 목록을 불러오지 못했습니다.",
    "en": "Could not load weapons and ranges.",
    "ja": "ブキと射程を読み込めませんでした。",
    "de": "Waffen und Reichweiten konnten nicht geladen werden.",
    "es": "No se pudieron cargar las armas y alcances.",
    "fr": "Impossible de charger les armes et les portées.",
    "it": "Impossibile caricare armi e portate.",
    "nl": "Wapens en bereik konden niet worden geladen.",
    "ru": "Не удалось загрузить оружие и дальность.",
    "zh-Hans": "无法加载武器与射程。",
    "zh-Hant": "無法載入武器與射程。"
  },
  "청록": {
    "ko": "청록",
    "en": "Teal",
    "ja": "青緑",
    "de": "Türkis",
    "es": "Verde azulado",
    "fr": "Turquoise",
    "it": "Verde acqua",
    "nl": "Blauwgroen",
    "ru": "Бирюзовый",
    "zh-Hans": "青绿",
    "zh-Hant": "青綠"
  },
  "보라": {
    "ko": "보라",
    "en": "Purple",
    "ja": "紫",
    "de": "Violett",
    "es": "Morado",
    "fr": "Violet",
    "it": "Viola",
    "nl": "Paars",
    "ru": "Фиолетовый",
    "zh-Hans": "紫",
    "zh-Hant": "紫"
  },
  "{n}칸": {
    "ko": "{n}칸",
    "en": "{n} lines",
    "ja": "{n}ライン",
    "de": "{n} Linien",
    "es": "{n} líneas",
    "fr": "{n} lignes",
    "it": "{n} linee",
    "nl": "{n} lijnen",
    "ru": "{n} линий",
    "zh-Hans": "{n}格",
    "zh-Hant": "{n}格"
  },
  "타워 관문 {n}": {
    "ko": "타워 관문 {n}",
    "en": "Tower checkpoint {n}",
    "ja": "ヤグラのカンモン {n}",
    "de": "Turmkontrollpunkt {n}",
    "es": "Punto de control de torre {n}",
    "fr": "Point de contrôle de la tour {n}",
    "it": "Checkpoint della torre {n}",
    "nl": "Torencontrolepunt {n}",
    "ru": "Контрольная точка башни {n}",
    "zh-Hans": "塔楼关卡 {n}",
    "zh-Hant": "塔樓關卡 {n}"
  },
  "골": {
    "ko": "골",
    "en": "Goal",
    "ja": "ゴール",
    "de": "Ziel",
    "es": "Meta",
    "fr": "Arrivée",
    "it": "Traguardo",
    "nl": "Doel",
    "ru": "Финиш",
    "zh-Hans": "终点",
    "zh-Hant": "終點"
  },
  "관문": {
    "ko": "관문",
    "en": "Checkpoint",
    "ja": "カンモン",
    "de": "Kontrollpunkt",
    "es": "Punto de control",
    "fr": "Point de contrôle",
    "it": "Checkpoint",
    "nl": "Controlepunt",
    "ru": "Контрольная точка",
    "zh-Hans": "关卡",
    "zh-Hant": "關卡"
  },
  "바지락 골": {
    "ko": "바지락 골",
    "en": "Clam basket",
    "ja": "アサリゴール",
    "de": "Muschelkorb",
    "es": "Canasta de almejas",
    "fr": "Panier à palourdes",
    "it": "Canestro delle vongole",
    "nl": "Schelpenmand",
    "ru": "Корзина для устриц",
    "zh-Hans": "蛤蜊球篮",
    "zh-Hant": "蛤蜊球籃"
  },
  "에어리어": {
    "ko": "에어리어",
    "en": "Zone",
    "ja": "エリア",
    "de": "Zone",
    "es": "Zona",
    "fr": "Zone",
    "it": "Zona",
    "nl": "Zone",
    "ru": "Зона",
    "zh-Hans": "区域",
    "zh-Hant": "區域"
  },
  "타워": {
    "ko": "타워",
    "en": "Tower",
    "ja": "ヤグラ",
    "de": "Turm",
    "es": "Torre",
    "fr": "Tour",
    "it": "Torre",
    "nl": "Toren",
    "ru": "Башня",
    "zh-Hans": "塔楼",
    "zh-Hant": "塔樓"
  },
  "피시": {
    "ko": "피시",
    "en": "Rainmaker",
    "ja": "ホコ",
    "de": "Goldfisch",
    "es": "Pez dorado",
    "fr": "Bazookarpe",
    "it": "Bazookarp",
    "nl": "Bazookarper",
    "ru": "Мегакарп",
    "zh-Hans": "鱼虎",
    "zh-Hant": "魚虎"
  },
  "가로 베기 · 잉크": {
    "ko": "가로 베기 · 잉크",
    "en": "Horizontal slash · ink",
    "ja": "ヨコ斬り・インク",
    "de": "Horizontaler Hieb · Tinte",
    "es": "Corte horizontal · tinta",
    "fr": "Entaille horizontale · encre",
    "it": "Fendente orizzontale · inchiostro",
    "nl": "Horizontale slag · inkt",
    "ru": "Горизонтальный удар · чернила",
    "zh-Hans": "横斩 · 墨汁",
    "zh-Hant": "橫斬 · 墨汁"
  },
  "가로 휘두르기": {
    "ko": "가로 휘두르기",
    "en": "Horizontal swing",
    "ja": "ヨコ振り",
    "de": "Horizontaler Schwung",
    "es": "Golpe horizontal",
    "fr": "Frappe horizontale",
    "it": "Colpo orizzontale",
    "nl": "Horizontale zwaai",
    "ru": "Горизонтальный взмах",
    "zh-Hans": "横挥",
    "zh-Hant": "橫揮"
  },
  "단거리 모드": {
    "ko": "단거리 모드",
    "en": "Short-range mode",
    "ja": "短射程モード",
    "de": "Kurzstreckenmodus",
    "es": "Modo de corto alcance",
    "fr": "Mode courte portée",
    "it": "Modalità a corto raggio",
    "nl": "Kortbereikstand",
    "ru": "Ближний режим",
    "zh-Hans": "短射程模式",
    "zh-Hant": "短射程模式"
  },
  "대미지 도달": {
    "ko": "대미지 도달",
    "en": "Damage reach",
    "ja": "ダメージ到達距離",
    "de": "Schadensreichweite",
    "es": "Alcance del daño",
    "fr": "Portée des dégâts",
    "it": "Portata del danno",
    "nl": "Schadebereik",
    "ru": "Дальность урона",
    "zh-Hans": "伤害可达距离",
    "zh-Hant": "傷害可達距離"
  },
  "세로 휘두르기": {
    "ko": "세로 휘두르기",
    "en": "Vertical swing",
    "ja": "タテ振り",
    "de": "Vertikaler Schwung",
    "es": "Golpe vertical",
    "fr": "Frappe verticale",
    "it": "Colpo verticale",
    "nl": "Verticale zwaai",
    "ru": "Вертикальный взмах",
    "zh-Hans": "纵挥",
    "zh-Hant": "縱揮"
  },
  "소용돌이 포함": {
    "ko": "소용돌이 포함",
    "en": "Including vortex",
    "ja": "渦を含む",
    "de": "Mit Wirbel",
    "es": "Incluye remolino",
    "fr": "Tourbillon inclus",
    "it": "Vortice incluso",
    "nl": "Inclusief draaikolk",
    "ru": "Включая вихрь",
    "zh-Hans": "含漩涡",
    "zh-Hant": "含漩渦"
  },
  "슬라이드 전": {
    "ko": "슬라이드 전",
    "en": "Before dodge roll",
    "ja": "スライド前",
    "de": "Vor der Ausweichrolle",
    "es": "Antes de rodar",
    "fr": "Avant la roulade",
    "it": "Prima della schivata",
    "nl": "Voor de ontwijkrol",
    "ru": "До кувырка",
    "zh-Hans": "滑步前",
    "zh-Hant": "滑步前"
  },
  "슬라이드 후": {
    "ko": "슬라이드 후",
    "en": "After dodge roll",
    "ja": "スライド後",
    "de": "Nach der Ausweichrolle",
    "es": "Después de rodar",
    "fr": "Après la roulade",
    "it": "Dopo la schivata",
    "nl": "Na de ontwijkrol",
    "ru": "После кувырка",
    "zh-Hans": "滑步后",
    "zh-Hant": "滑步後"
  },
  "연속 사격": {
    "ko": "연속 사격",
    "en": "Continuous fire",
    "ja": "連続射撃",
    "de": "Dauerfeuer",
    "es": "Disparo continuo",
    "fr": "Tir continu",
    "it": "Fuoco continuo",
    "nl": "Continu vuren",
    "ru": "Непрерывная стрельба",
    "zh-Hans": "连续射击",
    "zh-Hant": "連續射擊"
  },
  "유효 사거리": {
    "ko": "유효 사거리",
    "en": "Effective range",
    "ja": "有効射程",
    "de": "Effektive Reichweite",
    "es": "Alcance efectivo",
    "fr": "Portée effective",
    "it": "Portata effettiva",
    "nl": "Effectief bereik",
    "ru": "Эффективная дальность",
    "zh-Hans": "有效射程",
    "zh-Hant": "有效射程"
  },
  "장거리 모드": {
    "ko": "장거리 모드",
    "en": "Long-range mode",
    "ja": "長射程モード",
    "de": "Langstreckenmodus",
    "es": "Modo de largo alcance",
    "fr": "Mode longue portée",
    "it": "Modalità a lungo raggio",
    "nl": "Langbereikstand",
    "ru": "Дальний режим",
    "zh-Hans": "长射程模式",
    "zh-Hant": "長射程模式"
  },
  "점프 사격 · 폭발 포함": {
    "ko": "점프 사격 · 폭발 포함",
    "en": "Jump shot · including blast",
    "ja": "ジャンプ撃ち・爆風込み",
    "de": "Sprungschuss · mit Explosion",
    "es": "Disparo en salto · incluye explosión",
    "fr": "Tir sauté · explosion incluse",
    "it": "Tiro in salto · esplosione inclusa",
    "nl": "Sprongschot · inclusief explosie",
    "ru": "Стрельба в прыжке · со взрывом",
    "zh-Hans": "跳跃射击 · 含爆炸",
    "zh-Hant": "跳躍射擊 · 含爆炸"
  },
  "지상 사격 · 폭발 포함": {
    "ko": "지상 사격 · 폭발 포함",
    "en": "Ground shot · including blast",
    "ja": "地上撃ち・爆風込み",
    "de": "Bodenschuss · mit Explosion",
    "es": "Disparo en suelo · incluye explosión",
    "fr": "Tir au sol · explosion incluse",
    "it": "Tiro a terra · esplosione inclusa",
    "nl": "Grondschot · inclusief explosie",
    "ru": "Стрельба с земли · со взрывом",
    "zh-Hans": "地面射击 · 含爆炸",
    "zh-Hant": "地面射擊 · 含爆炸"
  },
  "차지 베기 · 잉크": {
    "ko": "차지 베기 · 잉크",
    "en": "Charged slash · ink",
    "ja": "タメ斬り・インク",
    "de": "Aufgeladener Hieb · Tinte",
    "es": "Corte cargado · tinta",
    "fr": "Entaille chargée · encre",
    "it": "Fendente caricato · inchiostro",
    "nl": "Opgeladen slag · inkt",
    "ru": "Заряженный удар · чернила",
    "zh-Hans": "蓄力斩 · 墨汁",
    "zh-Hant": "蓄力斬 · 墨汁"
  },
  "첫 발": {
    "ko": "첫 발",
    "en": "First shot",
    "ja": "初弾",
    "de": "Erster Schuss",
    "es": "Primer disparo",
    "fr": "Premier tir",
    "it": "Primo colpo",
    "nl": "Eerste schot",
    "ru": "Первый выстрел",
    "zh-Hans": "首发",
    "zh-Hant": "首發"
  },
  "폭발 포함": {
    "ko": "폭발 포함",
    "en": "Including blast",
    "ja": "爆風込み",
    "de": "Mit Explosion",
    "es": "Incluye explosión",
    "fr": "Explosion incluse",
    "it": "Esplosione inclusa",
    "nl": "Inclusief explosie",
    "ru": "Включая взрыв",
    "zh-Hans": "含爆炸",
    "zh-Hant": "含爆炸"
  },
  "풀차지": {
    "ko": "풀차지",
    "en": "Full charge",
    "ja": "フルチャージ",
    "de": "Voll aufgeladen",
    "es": "Carga completa",
    "fr": "Charge complète",
    "it": "Carica completa",
    "nl": "Volledig opgeladen",
    "ru": "Полный заряд",
    "zh-Hans": "完全蓄力",
    "zh-Hant": "完全蓄力"
  },
  "풀차지 · 폭발 포함": {
    "ko": "풀차지 · 폭발 포함",
    "en": "Full charge · including blast",
    "ja": "フルチャージ・爆風込み",
    "de": "Voll aufgeladen · mit Explosion",
    "es": "Carga completa · incluye explosión",
    "fr": "Charge complète · explosion incluse",
    "it": "Carica completa · esplosione inclusa",
    "nl": "Volledig opgeladen · inclusief explosie",
    "ru": "Полный заряд · со взрывом",
    "zh-Hans": "完全蓄力 · 含爆炸",
    "zh-Hant": "完全蓄力 · 含爆炸"
  }
};
Object.assign(messages,{"드래그 또는 방향키로 이동, 오른쪽 드래그로 회전, 더하기와 빼기로 확대 축소": {"ko": "드래그 또는 방향키로 이동, 오른쪽 드래그로 회전, 더하기와 빼기로 확대 축소", "en": "Drag or arrow keys to pan; right-drag to rotate; plus/minus to zoom", "ja": "ドラッグ・矢印キーで移動、右ドラッグで回転、＋／−で拡大縮小", "de": "Ziehen oder Pfeiltasten zum Verschieben; rechts ziehen zum Drehen; Plus/Minus zum Zoomen", "es": "Arrastra o usa flechas para mover; arrastra con botón derecho para girar; más/menos para ampliar", "fr": "Glisser ou flèches pour déplacer ; glisser avec le bouton droit pour pivoter ; plus/moins pour zoomer", "it": "Trascina o usa le frecce per spostare; trascina col tasto destro per ruotare; più/meno per zoomare", "nl": "Sleep of gebruik pijltjes om te verplaatsen; rechts slepen om te draaien; plus/min om te zoomen", "ru": "Перетаскивание или стрелки — перемещение; правая кнопка — вращение; плюс/минус — масштаб", "zh-Hans": "拖动或方向键移动，右键拖动旋转，加减键缩放", "zh-Hant": "拖曳或方向鍵移動，右鍵拖曳旋轉，加減鍵縮放"}, "드래그 또는 방향키로 회전, Shift와 함께 이동, 더하기와 빼기로 확대 축소": {"ko": "드래그 또는 방향키로 회전, Shift와 함께 이동, 더하기와 빼기로 확대 축소", "en": "Drag or arrow keys to rotate; hold Shift to pan; plus/minus to zoom", "ja": "ドラッグ・矢印キーで回転、Shiftで移動、＋／−で拡大縮小", "de": "Ziehen oder Pfeiltasten zum Drehen; Umschalt zum Verschieben; Plus/Minus zum Zoomen", "es": "Arrastra o usa flechas para girar; mantén Mayús para mover; más/menos para ampliar", "fr": "Glisser ou flèches pour pivoter ; maintenir Maj pour déplacer ; plus/moins pour zoomer", "it": "Trascina o usa le frecce per ruotare; tieni Maiusc per spostare; più/meno per zoomare", "nl": "Sleep of gebruik pijltjes om te draaien; houd Shift vast om te verplaatsen; plus/min om te zoomen", "ru": "Перетаскивание или стрелки — вращение; Shift — перемещение; плюс/минус — масштаб", "zh-Hans": "拖动或方向键旋转，按住Shift移动，加减键缩放", "zh-Hant": "拖曳或方向鍵旋轉，按住Shift移動，加減鍵縮放"}});
Object.assign(messages,{
  "서브": {
    "ko": "서브",
    "en": "Sub",
    "ja": "サブ",
    "de": "Sekundär",
    "es": "Secundarias",
    "fr": "Secondaires",
    "it": "Secondarie",
    "nl": "Subwapens",
    "ru": "Дополнительное",
    "zh-Hans": "副武器",
    "zh-Hant": "副武器"
  },
  "스페셜": {
    "ko": "스페셜",
    "en": "Special",
    "ja": "スペシャル",
    "de": "Spezial",
    "es": "Especiales",
    "fr": "Spéciales",
    "it": "Speciali",
    "nl": "Specials",
    "ru": "Специальное",
    "zh-Hans": "特殊武器",
    "zh-Hant": "特殊武器"
  },
  "범위 반지름": {
    "ko": "범위 반지름",
    "en": "Effect radius",
    "ja": "範囲半径",
    "de": "Effektradius",
    "es": "Radio de efecto",
    "fr": "Rayon d’effet",
    "it": "Raggio effetto",
    "nl": "Effectstraal",
    "ru": "Радиус действия",
    "zh-Hans": "效果半径",
    "zh-Hant": "效果半徑"
  },
  "감지 반지름": {
    "ko": "감지 반지름",
    "en": "Detection radius",
    "ja": "感知半径",
    "de": "Erkennungsradius",
    "es": "Radio de detección",
    "fr": "Rayon de détection",
    "it": "Raggio rilevamento",
    "nl": "Detectiestraal",
    "ru": "Радиус обнаружения",
    "zh-Hans": "感应半径",
    "zh-Hant": "感應半徑"
  },
  "폭발 반지름": {
    "ko": "폭발 반지름",
    "en": "Blast radius",
    "ja": "爆風半径",
    "de": "Explosionsradius",
    "es": "Radio de explosión",
    "fr": "Rayon d’explosion",
    "it": "Raggio esplosione",
    "nl": "Explosiestraal",
    "ru": "Радиус взрыва",
    "zh-Hans": "爆炸半径",
    "zh-Hant": "爆炸半徑"
  },
  "주황": {
    "ko": "주황",
    "en": "Orange",
    "ja": "オレンジ",
    "de": "Orange",
    "es": "Naranja",
    "fr": "Orange",
    "it": "Arancione",
    "nl": "Oranje",
    "ru": "Оранжевый",
    "zh-Hans": "橙色",
    "zh-Hant": "橙色"
  },
  "평면 근사": {
    "ko": "평면 근사",
    "en": "Flat approximation",
    "ja": "平面近似",
    "de": "Ebene Näherung",
    "es": "Aproximación plana",
    "fr": "Approximation plane",
    "it": "Approssimazione piana",
    "nl": "Vlakke benadering",
    "ru": "Плоское приближение",
    "zh-Hans": "平面近似",
    "zh-Hant": "平面近似"
  },
  "높이": {
    "ko": "높이",
    "en": "Height",
    "ja": "高さ",
    "de": "Höhe",
    "es": "Altura",
    "fr": "Hauteur",
    "it": "Altezza",
    "nl": "Hoogte",
    "ru": "Высота",
    "zh-Hans": "高度",
    "zh-Hant": "高度"
  },
  "1발": {
    "ko": "1발",
    "en": "One strike",
    "ja": "1発",
    "de": "Ein Einschlag",
    "es": "Un impacto",
    "fr": "Un impact",
    "it": "Un colpo",
    "nl": "Eén inslag",
    "ru": "Один удар",
    "zh-Hans": "单发",
    "zh-Hant": "單發"
  },
  "방향 손잡이를 드래그해서 회전": {
    "ko": "방향 손잡이를 드래그해서 회전",
    "en": "Drag the direction handle to rotate",
    "ja": "方向ハンドルをドラッグして回転",
    "de": "Richtungsgriff zum Drehen ziehen",
    "es": "Arrastra el control de dirección para girar",
    "fr": "Glisser la poignée de direction pour pivoter",
    "it": "Trascina la maniglia di direzione per ruotare",
    "nl": "Sleep de richtingsgreep om te draaien",
    "ru": "Перетащите ручку направления для поворота",
    "zh-Hans": "拖动方向手柄旋转",
    "zh-Hant": "拖曳方向控制點旋轉"
  }
});
Object.assign(messages,{"서브·스페셜 범위 출처": {"ko": "서브·스페셜 범위 출처", "en": "Sub/special range sources", "ja": "サブ・スペシャルの範囲出典", "de": "Quellen für Sekundär- und Spezialbereiche", "es": "Fuentes de alcance de secundarias y especiales", "fr": "Sources des portées secondaires et spéciales", "it": "Fonti portate secondarie e speciali", "nl": "Bronnen sub- en specialbereik", "ru": "Источники радиусов доп. и спец. оружия", "zh-Hans": "副武器与特殊武器范围来源", "zh-Hant": "副武器與特殊武器範圍來源"}});
Object.assign(messages,{"파랑": {"ko": "파랑", "en": "Blue", "ja": "青", "de": "Blau", "es": "Azul", "fr": "Bleu", "it": "Blu", "nl": "Blauw", "ru": "Синий", "zh-Hans": "蓝色", "zh-Hant": "藍色"}});
Object.assign(messages,{"이동 거리": {"ko": "이동 거리", "en": "Travel distance", "ja": "移動距離", "de": "Bewegungsstrecke", "es": "Distancia de avance", "fr": "Distance parcourue", "it": "Distanza percorsa", "nl": "Reisafstand", "ru": "Дальность движения", "zh-Hans": "移动距离", "zh-Hant": "移動距離"}, "출발점을 드래그해서 레일 조정": {"ko": "출발점을 드래그해서 레일 조정", "en": "Drag the start point to adjust the rails", "ja": "始点をドラッグしてレールを調整", "de": "Startpunkt ziehen, um die Schienen anzupassen", "es": "Arrastra el inicio para ajustar los raíles", "fr": "Glisser le départ pour ajuster les rails", "it": "Trascina la partenza per regolare i binari", "nl": "Sleep het startpunt om de rails aan te passen", "ru": "Перетащите начальную точку для настройки рельсов", "zh-Hans": "拖动起点调整轨道", "zh-Hant": "拖曳起點調整軌道"}});
Object.assign(messages,{
  "닫기": {
    "ko": "닫기",
    "en": "Close",
    "ja": "閉じる",
    "de": "Schließen",
    "es": "Cerrar",
    "fr": "Fermer",
    "it": "Chiudi",
    "nl": "Sluiten",
    "ru": "Закрыть",
    "zh-Hans": "关闭",
    "zh-Hant": "關閉"
  },
  "삭제": {
    "ko": "삭제",
    "en": "Delete",
    "ja": "削除",
    "de": "Löschen",
    "es": "Eliminar",
    "fr": "Supprimer",
    "it": "Elimina",
    "nl": "Verwijderen",
    "ru": "Удалить",
    "zh-Hans": "删除",
    "zh-Hant": "刪除"
  },
  "마커 배경": {
    "ko": "마커 배경",
    "en": "Marker background",
    "ja": "マーカーの背景",
    "de": "Markierungshintergrund",
    "es": "Fondo del marcador",
    "fr": "Fond du marqueur",
    "it": "Sfondo indicatore",
    "nl": "Markerachtergrond",
    "ru": "Фон маркера",
    "zh-Hans": "标记背景",
    "zh-Hant": "標記背景"
  },
  "기본값": {
    "ko": "기본값",
    "en": "Default",
    "ja": "初期値",
    "de": "Standard",
    "es": "Predeterminado",
    "fr": "Par défaut",
    "it": "Predefinito",
    "nl": "Standaard",
    "ru": "По умолчанию",
    "zh-Hans": "默认",
    "zh-Hant": "預設"
  },
  "서브 성능 업": {
    "ko": "서브 성능 업",
    "en": "Sub Power Up",
    "ja": "サブ性能アップ",
    "de": "Sekundärstärke +",
    "es": "Potenciador secundario",
    "fr": "Arme secondaire +",
    "it": "Arma secondaria +",
    "nl": "Subkracht omhoog",
    "ru": "Усиление доп. оружия",
    "zh-Hans": "提升次要武器性能",
    "zh-Hant": "提升次要武器性能"
  },
  "스페셜 성능 업": {
    "ko": "스페셜 성능 업",
    "en": "Special Power Up",
    "ja": "スペシャル性能アップ",
    "de": "Spezialstärke +",
    "es": "Potenciador especial",
    "fr": "Arme spéciale +",
    "it": "Arma speciale +",
    "nl": "Specialkracht omhoog",
    "ru": "Усиление спец. оружия",
    "zh-Hans": "提升特殊武器性能",
    "zh-Hant": "提升特殊武器性能"
  },
  "우클릭으로 마커 설정": {
    "ko": "우클릭으로 마커 설정",
    "en": "Right-click for marker settings",
    "ja": "右クリックでマーカー設定",
    "de": "Rechtsklick für Markierungseinstellungen",
    "es": "Clic derecho para configurar el marcador",
    "fr": "Clic droit pour régler le marqueur",
    "it": "Clic destro per le impostazioni dell’indicatore",
    "nl": "Rechtsklik voor markerinstellingen",
    "ru": "Правый клик для настройки маркера",
    "zh-Hans": "右键打开标记设置",
    "zh-Hant": "按右鍵開啟標記設定"
  }
});
Object.assign(messages,{
  "마커 링크 복사": {
    "ko": "마커 링크 복사",
    "en": "Copy marker link",
    "ja": "マーカーリンクをコピー",
    "de": "Markierungslink kopieren",
    "es": "Copiar enlace de marcadores",
    "fr": "Copier le lien des marqueurs",
    "it": "Copia link indicatori",
    "nl": "Markerlink kopiëren",
    "ru": "Копировать ссылку на маркеры",
    "zh-Hans": "复制标记链接",
    "zh-Hant": "複製標記連結"
  },
  "마커 링크를 복사했습니다.": {
    "ko": "마커 링크를 복사했습니다.",
    "en": "Marker link copied.",
    "ja": "マーカーリンクをコピーしました。",
    "de": "Markierungslink kopiert.",
    "es": "Enlace de marcadores copiado.",
    "fr": "Lien des marqueurs copié.",
    "it": "Link indicatori copiato.",
    "nl": "Markerlink gekopieerd.",
    "ru": "Ссылка на маркеры скопирована.",
    "zh-Hans": "已复制标记链接。",
    "zh-Hant": "已複製標記連結。"
  },
  "마커 링크를 복사해 주세요.": {
    "ko": "마커 링크를 복사해 주세요.",
    "en": "Copy this marker link.",
    "ja": "マーカーリンクをコピーしてください。",
    "de": "Diesen Markierungslink kopieren.",
    "es": "Copia este enlace de marcadores.",
    "fr": "Copiez ce lien des marqueurs.",
    "it": "Copia questo link degli indicatori.",
    "nl": "Kopieer deze markerlink.",
    "ru": "Скопируйте ссылку на маркеры.",
    "zh-Hans": "请复制此标记链接。",
    "zh-Hant": "請複製此標記連結。"
  },
  "마커 링크를 불러오지 못했습니다.": {
    "ko": "마커 링크를 불러오지 못했습니다.",
    "en": "Could not load the marker link.",
    "ja": "マーカーリンクを読み込めませんでした。",
    "de": "Markierungslink konnte nicht geladen werden.",
    "es": "No se pudo cargar el enlace de marcadores.",
    "fr": "Impossible de charger le lien des marqueurs.",
    "it": "Impossibile caricare il link degli indicatori.",
    "nl": "Kon de markerlink niet laden.",
    "ru": "Не удалось загрузить ссылку на маркеры.",
    "zh-Hans": "无法加载标记链接。",
    "zh-Hant": "無法載入標記連結。"
  }
});
Object.assign(messages,{"마커 링크를 만들지 못했습니다.": {"ko": "마커 링크를 만들지 못했습니다.", "en": "Could not create the marker link.", "ja": "マーカーリンクを作成できませんでした。", "de": "Markierungslink konnte nicht erstellt werden.", "es": "No se pudo crear el enlace de marcadores.", "fr": "Impossible de créer le lien des marqueurs.", "it": "Impossibile creare il link degli indicatori.", "nl": "Kon de markerlink niet maken.", "ru": "Не удалось создать ссылку на маркеры.", "zh-Hans": "无法创建标记链接。", "zh-Hant": "無法建立標記連結。"}});
Object.assign(messages,{"배치한 마커가 모두 사라집니다. 계속하시겠습니까?": {"ko": "배치한 마커가 모두 사라집니다. 계속하시겠습니까?", "en": "All placed markers will be removed. Continue?", "ja": "配置したマーカーがすべて消えます。続行しますか？", "de": "Alle platzierten Markierungen werden entfernt. Fortfahren?", "es": "Se eliminarán todos los marcadores colocados. ¿Continuar?", "fr": "Tous les marqueurs placés seront supprimés. Continuer ?", "it": "Tutti gli indicatori posizionati verranno rimossi. Continuare?", "nl": "Alle geplaatste markers worden verwijderd. Doorgaan?", "ru": "Все размещённые маркеры будут удалены. Продолжить?", "zh-Hans": "所有已放置的标记都将被移除。是否继续？", "zh-Hant": "所有已放置的標記都將被移除。是否繼續？"}});
const groups={KRko:'ko',JPja:'ja',USen:'en',EUen:'en',EUde:'de',EUes:'es',USes:'es',EUfr:'fr',USfr:'fr',EUit:'it',EUnl:'nl',EUru:'ru',CNzh:'zh-Hans',TWzh:'zh-Hant'};
let language='ko';
const aliases={'언어':'language','전체':'all','정렬':'sort','게임 순서':'defaultSort','이름순':'nameSort','초기화':'reset','비공식 팬 페이지 · 게임 이미지와 문구 © Nintendo':'footer','다시 시도':'retry','다시 불러오기':'retry'};
function t(key,values={}){
 let text=messages[key]?.[language] ?? window.WEAPON_UI?.[language]?.[aliases[key]] ?? key;
 for(const [name,value] of Object.entries(values))text=text.replaceAll('{'+name+'}',String(value));
 return text;
}
function text(node,key){node.dataset.l10n=key;node.textContent=t(key)}
function apply(){
 document.querySelectorAll('[data-l10n]').forEach(node=>node.textContent=t(node.dataset.l10n));
 for(const attr of ['aria-label','title','placeholder'])document.querySelectorAll('[data-l10n-'+attr+']').forEach(node=>node.setAttribute(attr,t(node.getAttribute('data-l10n-'+attr))));
}
function setLanguage(code){language=groups[code]||'ko';document.documentElement.lang=language;apply();document.dispatchEvent(new Event('localizationchange'))}
window.SITE_I18N={t,text,apply,setLanguage,groups,messages,number:value=>new Intl.NumberFormat(language).format(value)};
})();
