/* Interface translations. Game names and dialogue come directly from Leanny/splat3. */
window.WEAPON_UI = {};
const uiKeys = 'title|language|search|searchHint|type|all|sort|defaultSort|nameSort|spSort|rankSort|reset|results|empty|emptyHint|close|sub|special|sp|rank|specialUnlock|explanation|performance|barsNote|numbers|matchRange|rangeNote|raw|source|footer|missing|loading|error|retry|seconds|internal'.split('|');
function ui(lang, text, stats) {
  const values = text.split('|');
  if (values.length !== uiKeys.length) throw new Error('UI key count: ' + lang);
  window.WEAPON_UI[lang] = Object.fromEntries(uiKeys.map((k, i) => [k, values[i]]));
  window.WEAPON_UI[lang].stats = Object.fromEntries(statKeys.map((k, i) => [k, stats.split('|')[i]]));
  Object.assign(window.WEAPON_UI[lang], Object.fromEntries(guideKeys.map((key, i) => [key, guideTranslations[lang][i]])));
}
const statKeys = 'damageMax|damageMin|fullDamage|blastDamage|partialDamage|unchargedDamage|travelFull|horizontalDamage|verticalDamage|rollDamage|horizontalContact|verticalContact|shotTotal|pelletDamage|fullArrow|unchargedArrow|unitDamage|ink|inkFull|inkMin|repeat|recovery|charge|chargeFirst|chargeSecond|slideInk|slideRepeat'.split('|');
const guideTranslations = {
  ko:['관련 공략','메인 관련 공략','서브 관련 공략','스페셜 관련 공략','아직 등록된 공략이 없습니다.','공략을 불러오는 중…','공략을 불러오지 못했습니다.'],
  en:['Related guides','Main weapon guides','Sub weapon guides','Special weapon guides','No guides added yet.','Loading guides…','Could not load guides.'],
  ja:['関連攻略','メインウェポンの攻略','サブウェポンの攻略','スペシャルウェポンの攻略','攻略はまだ登録されていません。','攻略を読み込み中…','攻略を読み込めませんでした。'],
  de:['Passende Guides','Guides zur Hauptwaffe','Guides zur Sekundärwaffe','Guides zur Spezialwaffe','Noch keine Guides vorhanden.','Guides werden geladen…','Guides konnten nicht geladen werden.'],
  es:['Guías relacionadas','Guías del arma principal','Guías del arma secundaria','Guías del arma especial','Aún no hay guías.','Cargando guías…','No se pudieron cargar las guías.'],
  fr:['Guides associés','Guides de l’arme principale','Guides de l’arme secondaire','Guides de l’arme spéciale','Aucun guide pour le moment.','Chargement des guides…','Impossible de charger les guides.'],
  it:['Guide correlate','Guide dell’arma principale','Guide dell’arma secondaria','Guide dell’arma speciale','Nessuna guida ancora disponibile.','Caricamento delle guide…','Impossibile caricare le guide.'],
  nl:['Gerelateerde gidsen','Gidsen voor het hoofdwapen','Gidsen voor het subwapen','Gidsen voor het speciale wapen','Er zijn nog geen gidsen toegevoegd.','Gidsen laden…','De gidsen konden niet worden geladen.'],
  ru:['Связанные руководства','Основное оружие','Вспомогательное оружие','Специальное оружие','Руководства пока не добавлены.','Загрузка руководств…','Не удалось загрузить руководства.'],
  'zh-Hans':['相关攻略','主武器攻略','副武器攻略','特殊武器攻略','暂无攻略。','正在加载攻略…','无法加载攻略。'],
  'zh-Hant':['相關攻略','主武器攻略','次要武器攻略','特殊武器攻略','尚無攻略。','正在載入攻略…','無法載入攻略。']
};
const guideKeys = ['guides','guidesMain','guidesSub','guidesSpecial','guidesEmpty','guidesLoading','guidesError'];
ui('ko', '무기 진열장|언어|무기 검색|무기 · 서브 · 스페셜 이름|무기 종류|전체|정렬|게임 순서|이름순|필요 SP순|해금 랭크순|초기화|개 무기|일치하는 무기가 없습니다.|검색어나 무기 종류를 바꿔 보세요.|닫기|서브 웨펀|스페셜 웨펀|필요 SP|해금 랭크|일반 랭크 해금 없음|무기 설명|무기 성능|실제 무기 성능과 다를 수 있습니다|상세 수치|매칭용 사거리|사거리는 팀 매칭용 내부값입니다. 실제 유효 사거리와 다를 수 있습니다|원본 파라미터|데이터 출처|비공식 팬 페이지 · 게임 이미지와 문구 © Nintendo|이 무기는 설명이 필요없슴다!|데이터를 불러오는 중…|데이터를 읽지 못했습니다. 파일이 모두 있는지 확인하고 다시 열어 주세요.|다시 열기|초|내부 단위',
'최대 탄 대미지|최소 탄 대미지|풀 차지 탄 대미지|폭발 대미지|부분 차지 최대 대미지|노 차지 대미지|풀 차지 탄 이동 거리|가로 휘두르기 대미지|세로 휘두르기 대미지|굴리기 대미지|가로 근접 판정 대미지|세로 근접 판정 대미지|산탄 합계 상한|산탄 1발 최대 대미지|풀 차지 화살 1발|노 차지 화살 1발|개별 탄 최대 대미지|잉크 소비량|풀 차지 잉크 소비량|최소 차지 잉크 소비량|발사 간격|잉크 회복 정지|풀 차지 시간|1단계 차지 시간|2단계 차지 시간|슬라이드 잉크 소비량|슬라이드 후 발사 간격');
ui('en', 'Weapon shelf|Language|Find a weapon|Weapon, sub or special name|Weapon class|All|Sort|Game order|Name|Special points|Unlock level|Reset|weapons|No matching weapons.|Try another name or weapon class.|Close|Sub weapon|Special weapon|Special points|Unlock level|No standard level unlock|Weapon notes|Performance|May differ from actual weapon performance.|Detailed values|Matchmaking range|Range is an internal value used for team matchmaking. It may differ from effective firing range.|Source parameters|Data source|Unofficial fan page · Game images and text © Nintendo|This weapon needs no introduction!|Loading data…|Data could not be read. Check that all files are present, then reload.|Reload|s|internal units',
'Maximum bullet damage|Minimum bullet damage|Full-charge bullet damage|Blast damage|Maximum partial-charge damage|Uncharged damage|Full-charge bullet travel|Horizontal swing damage|Vertical swing damage|Rolling damage|Horizontal contact damage|Vertical contact damage|Shotgun total cap|Maximum pellet damage|Full-charge arrow damage|Uncharged arrow damage|Individual projectile max damage|Ink consumption|Full-charge ink consumption|Minimum-charge ink consumption|Shot interval|Ink recovery delay|Full charge time|First charge stage|Second charge stage|Dodge-roll ink consumption|Post-roll shot interval');
ui('ja', 'ブキの棚|言語|ブキを探す|ブキ・サブ・スペシャルの名前|ブキ種|すべて|並び順|ゲーム順|名前順|必要ポイント順|解放ランク順|リセット|件のブキ|該当するブキがありません。|検索語やブキ種を変更してください。|閉じる|サブウェポン|スペシャルウェポン|必要ポイント|解放ランク|通常のランク解放なし|ブキの解説|ブキの性能|実際のブキ性能とは異なる場合があります。|詳細数値|マッチング用射程|射程はチームのマッチング用内部値です。実際の有効射程とは異なる場合があります。|原本パラメーター|データ出典|非公式ファンページ · ゲーム画像・文章 © Nintendo|このブキに説明はいらないでし！|読み込み中…|データを読み込めません。ファイルが揃っているか確認し、再読み込みしてください。|再読み込み|秒|内部単位',
'弾の最大ダメージ|弾の最小ダメージ|フルチャージ弾ダメージ|爆風ダメージ|部分チャージ最大ダメージ|ノンチャージダメージ|フルチャージ弾の移動距離|ヨコ振りダメージ|タテ振りダメージ|塗り進みダメージ|ヨコ振り接触判定|タテ振り接触判定|散弾合計の上限|散弾1発の最大ダメージ|フルチャージ矢1発|ノンチャージ矢1発|個別弾の最大ダメージ|インク消費量|フルチャージインク消費量|最小チャージインク消費量|発射間隔|インク回復停止|フルチャージ時間|1段階目チャージ時間|2段階目チャージ時間|スライドインク消費量|スライド後の発射間隔');
ui('de', 'Waffenregal|Sprache|Waffe suchen|Name der Waffe, Sekundär- oder Spezialwaffe|Waffenklasse|Alle|Sortieren|Spielreihenfolge|Name|Spezialpunkte|Freischalt-Level|Zurücksetzen|Waffen|Keine passenden Waffen.|Versuche einen anderen Namen oder eine andere Klasse.|Schließen|Sekundärwaffe|Spezialwaffe|Spezialpunkte|Freischalt-Level|Keine normale Level-Freischaltung|Waffenbeschreibung|Leistung|Kann von der tatsächlichen Waffenleistung abweichen.|Detailwerte|Matchmaking-Reichweite|Die Reichweite ist ein interner Wert für die Teamzusammenstellung. Sie kann von der effektiven Schussreichweite abweichen.|Quellparameter|Datenquelle|Inoffizielle Fanseite · Spielbilder und Texte © Nintendo|Diese Waffe braucht keine Erklärung!|Daten werden geladen…|Daten nicht lesbar. Prüfe die Dateien und lade die Seite neu.|Neu laden|s|interne Einheiten',
'Maximaler Projektilschaden|Minimaler Projektilschaden|Schaden voll aufgeladen|Explosionsschaden|Maximalschaden teilgeladen|Schaden ungeladen|Projektilweg voll aufgeladen|Horizontaler Schwung|Vertikaler Schwung|Rollschaden|Horizontaler Kontaktschaden|Vertikaler Kontaktschaden|Schrot-Gesamtschadensgrenze|Maximaler Schaden pro Schrotkorn|Pfeilschaden voll aufgeladen|Pfeilschaden ungeladen|Maximalschaden einzelnes Projektil|Tintenverbrauch|Tintenverbrauch voll aufgeladen|Tintenverbrauch minimal geladen|Schussintervall|Tintenregenerationspause|Volle Ladezeit|Erste Ladestufe|Zweite Ladestufe|Tintenverbrauch Ausweichrolle|Schussintervall nach Rolle');
ui('es', 'Estante de armas|Idioma|Buscar arma|Nombre del arma, secundaria o especial|Clase de arma|Todas|Ordenar|Orden del juego|Nombre|Puntos especiales|Nivel de desbloqueo|Restablecer|armas|No hay armas coincidentes.|Prueba otro nombre o clase de arma.|Cerrar|Arma secundaria|Arma especial|Puntos especiales|Nivel de desbloqueo|Sin desbloqueo por nivel normal|Descripción del arma|Rendimiento|Puede diferir del rendimiento real del arma.|Valores detallados|Alcance de emparejamiento|El alcance es un valor interno para el emparejamiento de equipos. Puede diferir del alcance efectivo de disparo.|Parámetros originales|Fuente de datos|Página de fans no oficial · Imágenes y textos del juego © Nintendo|¡Esta arma no necesita explicación!|Cargando datos…|No se pudieron leer los datos. Comprueba los archivos y recarga la página.|Recargar|s|unidades internas',
'Daño máximo del proyectil|Daño mínimo del proyectil|Daño con carga completa|Daño de explosión|Daño máximo con carga parcial|Daño sin carga|Recorrido con carga completa|Daño del golpe horizontal|Daño del golpe vertical|Daño al rodar|Contacto horizontal|Contacto vertical|Límite total de perdigones|Daño máximo por perdigón|Flecha con carga completa|Flecha sin carga|Daño máximo por proyectil|Consumo de tinta|Tinta con carga completa|Tinta con carga mínima|Intervalo de disparo|Pausa de recuperación de tinta|Tiempo de carga completa|Primera etapa de carga|Segunda etapa de carga|Tinta de voltereta|Intervalo tras voltereta');
ui('fr', 'Étagère à armes|Langue|Chercher une arme|Nom de l’arme, secondaire ou spéciale|Catégorie|Toutes|Trier|Ordre du jeu|Nom|Points spéciaux|Niveau de déblocage|Réinitialiser|armes|Aucune arme correspondante.|Essayez un autre nom ou une autre catégorie.|Fermer|Arme secondaire|Arme spéciale|Points spéciaux|Niveau de déblocage|Pas de déblocage par niveau standard|Description de l’arme|Performances|Peut différer des performances réelles de l’arme.|Valeurs détaillées|Portée de matchmaking|La portée est une valeur interne utilisée pour la composition des équipes. Elle peut différer de la portée de tir effective.|Paramètres source|Source des données|Page de fans non officielle · Images et textes du jeu © Nintendo|Cette arme se passe de présentation !|Chargement…|Données illisibles. Vérifiez les fichiers puis rechargez la page.|Recharger|s|unités internes',
'Dégâts maximaux du projectile|Dégâts minimaux du projectile|Dégâts à charge complète|Dégâts d’explosion|Dégâts max. à charge partielle|Dégâts sans charge|Trajet à charge complète|Dégâts du coup horizontal|Dégâts du coup vertical|Dégâts en roulant|Contact horizontal|Contact vertical|Plafond total de grenaille|Dégâts max. par plomb|Flèche à charge complète|Flèche sans charge|Dégâts max. par projectile|Consommation d’encre|Encre à charge complète|Encre à charge minimale|Intervalle de tir|Délai de récupération d’encre|Temps de charge complète|Premier palier de charge|Second palier de charge|Encre par roulade|Intervalle après roulade');
ui('it', 'Scaffale delle armi|Lingua|Cerca un’arma|Nome dell’arma, secondaria o speciale|Categoria|Tutte|Ordina|Ordine del gioco|Nome|Punti speciali|Livello di sblocco|Ripristina|armi|Nessuna arma corrispondente.|Prova un altro nome o un’altra categoria.|Chiudi|Arma secondaria|Arma speciale|Punti speciali|Livello di sblocco|Nessuno sblocco per livello standard|Descrizione dell’arma|Prestazioni|Può differire dalle prestazioni effettive dell’arma.|Valori dettagliati|Gittata di abbinamento|La gittata è un valore interno per l’abbinamento delle squadre. Può differire dalla gittata di tiro effettiva.|Parametri originali|Fonte dei dati|Pagina fan non ufficiale · Immagini e testi del gioco © Nintendo|Quest’arma non ha bisogno di spiegazioni!|Caricamento…|Impossibile leggere i dati. Controlla i file e ricarica la pagina.|Ricarica|s|unità interne',
'Danno massimo del proiettile|Danno minimo del proiettile|Danno a carica completa|Danno da esplosione|Danno max. a carica parziale|Danno senza carica|Percorso a carica completa|Danno del colpo orizzontale|Danno del colpo verticale|Danno rotolando|Contatto orizzontale|Contatto verticale|Limite totale dei pallini|Danno massimo per pallino|Freccia a carica completa|Freccia senza carica|Danno massimo per proiettile|Consumo d’inchiostro|Inchiostro a carica completa|Inchiostro a carica minima|Intervallo di tiro|Pausa recupero inchiostro|Tempo di carica completa|Prima fase di carica|Seconda fase di carica|Inchiostro per schivata|Intervallo dopo schivata');
ui('nl', 'Wapenrek|Taal|Wapen zoeken|Naam van wapen, subwapen of speciaal wapen|Wapentype|Alle|Sorteren|Spelvolgorde|Naam|Speciale punten|Vrijspeellevel|Wissen|wapens|Geen passende wapens.|Probeer een andere naam of een ander wapentype.|Sluiten|Subwapen|Speciaal wapen|Speciale punten|Vrijspeellevel|Geen standaard levelontgrendeling|Wapenuitleg|Prestaties|Kan afwijken van de werkelijke wapenprestaties.|Detailwaarden|Matchmaking-bereik|Bereik is een interne waarde voor het samenstellen van teams. Het kan afwijken van het effectieve schietbereik.|Bronparameters|Databron|Onofficiële fanpagina · Spelbeelden en teksten © Nintendo|Dit wapen heeft geen uitleg nodig!|Gegevens laden…|Gegevens onleesbaar. Controleer de bestanden en laad opnieuw.|Herladen|s|interne eenheden',
'Maximale projectielschade|Minimale projectielschade|Schade volledig opgeladen|Explosieschade|Max. schade deels opgeladen|Schade ongeladen|Projectielafstand vol opgeladen|Horizontale zwaaischade|Verticale zwaaischade|Rolschade|Horizontale contactschade|Verticale contactschade|Totale hagelschadelimiet|Maximale schade per hagelkorrel|Pijlschade vol opgeladen|Pijlschade ongeladen|Max. schade per projectiel|Inktverbruik|Inkt bij volledige lading|Inkt bij minimale lading|Schotinterval|Inkt-herstelpauze|Volledige laadtijd|Eerste laadfase|Tweede laadfase|Inkt per ontwijkrol|Schotinterval na rol');
ui('ru', 'Стойка оружия|Язык|Найти оружие|Название оружия, бомбы или спецоружия|Класс оружия|Все|Сортировка|Порядок в игре|Название|Очки спецоружия|Уровень открытия|Сбросить|видов оружия|Оружие не найдено.|Измените запрос или класс оружия.|Закрыть|Дополнительное оружие|Спецоружие|Очки спецоружия|Уровень открытия|Нет обычного открытия по уровню|Описание оружия|Характеристики|Может отличаться от реальных характеристик оружия.|Подробные значения|Дальность для подбора|Дальность — внутреннее значение для подбора команд. Оно может отличаться от эффективной дальности стрельбы.|Исходные параметры|Источник данных|Неофициальная фан-страница · Игровые изображения и тексты © Nintendo|Это оружие не нуждается в объяснениях!|Загрузка данных…|Не удалось прочитать данные. Проверьте файлы и обновите страницу.|Обновить|с|внутренние единицы',
'Максимальный урон снаряда|Минимальный урон снаряда|Урон при полном заряде|Урон взрыва|Макс. урон частичного заряда|Урон без заряда|Путь снаряда с полным зарядом|Урон горизонтального взмаха|Урон вертикального взмаха|Урон при прокатывании|Горизонтальный контакт|Вертикальный контакт|Предел суммарного урона дроби|Макс. урон дробинки|Стрела с полным зарядом|Стрела без заряда|Макс. урон отдельного снаряда|Расход краски|Краска при полном заряде|Краска при минимальном заряде|Интервал выстрелов|Задержка восстановления краски|Время полного заряда|Первая стадия заряда|Вторая стадия заряда|Краска на перекат|Интервал после переката');
ui('zh-Hans', '武器陈列架|语言|搜索武器|主武器、次要武器或特殊武器名称|武器类别|全部|排序|游戏顺序|名称|特殊武器点数|解锁等级|重置|件武器|没有匹配的武器。|请更换搜索词或武器类别。|关闭|次要武器|特殊武器|所需点数|解锁等级|非普通等级解锁|武器介绍|武器性能|可能与武器的实际性能有所不同。|详细数值|匹配用射程|射程是用于队伍匹配的内部数值，可能与实际有效射程有所不同。|原始参数|数据来源|非官方粉丝页面 · 游戏图片及文字 © Nintendo|这把武器不需要说明啦！|正在加载数据…|无法读取数据。请检查文件是否完整，然后重新加载。|重新加载|秒|内部单位',
'弹丸最大伤害|弹丸最小伤害|满蓄力弹丸伤害|爆炸伤害|部分蓄力最大伤害|无蓄力伤害|满蓄力弹丸移动距离|横挥伤害|纵挥伤害|滚动伤害|横挥近战判定|纵挥近战判定|霰弹总伤害上限|单颗霰弹最大伤害|满蓄力单箭伤害|无蓄力单箭伤害|单个弹丸最大伤害|墨水消耗|满蓄力墨水消耗|最低蓄力墨水消耗|发射间隔|墨水恢复停止时间|满蓄力时间|第一阶段蓄力时间|第二阶段蓄力时间|滑步墨水消耗|滑步后发射间隔');
ui('zh-Hant', '武器陳列架|語言|搜尋武器|主武器、次要武器或特殊武器名稱|武器類別|全部|排序|遊戲順序|名稱|特殊武器點數|解鎖等級|重設|件武器|沒有符合的武器。|請更換搜尋詞或武器類別。|關閉|次要武器|特殊武器|所需點數|解鎖等級|非普通等級解鎖|武器介紹|武器性能|可能與武器的實際性能有所不同。|詳細數值|配對用射程|射程是用於隊伍配對的內部數值，可能與實際有效射程有所不同。|原始參數|資料來源|非官方粉絲頁面 · 遊戲圖片及文字 © Nintendo|這把武器不需要說明啦！|正在載入資料…|無法讀取資料。請檢查檔案是否完整，然後重新載入。|重新載入|秒|內部單位',
'彈丸最大傷害|彈丸最小傷害|滿蓄力彈丸傷害|爆炸傷害|部分蓄力最大傷害|無蓄力傷害|滿蓄力彈丸移動距離|橫揮傷害|縱揮傷害|滾動傷害|橫揮近戰判定|縱揮近戰判定|霰彈總傷害上限|單顆霰彈最大傷害|滿蓄力單箭傷害|無蓄力單箭傷害|單個彈丸最大傷害|墨水消耗|滿蓄力墨水消耗|最低蓄力墨水消耗|發射間隔|墨水恢復停止時間|滿蓄力時間|第一階段蓄力時間|第二階段蓄力時間|滑步墨水消耗|滑步後發射間隔');
